-- Production schema sync for upstream sync 2026-05-03.
-- This script is non-destructive: it only creates missing objects and adds missing columns.

CREATE TABLE IF NOT EXISTS public.patch_report (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_type varchar(16) NOT NULL,
  status integer NOT NULL DEFAULT 0,
  reason varchar(5007) NOT NULL,
  handler_reply varchar(5007) NOT NULL DEFAULT '',
  handled_at timestamp without time zone,
  sender_id integer NOT NULL,
  reported_user_id integer NOT NULL,
  handler_id integer,
  patch_id integer NOT NULL,
  comment_id integer,
  rating_id integer,
  created timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE public.patch_report
  ADD COLUMN IF NOT EXISTS target_type varchar(16) NOT NULL DEFAULT 'comment',
  ADD COLUMN IF NOT EXISTS status integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS reason varchar(5007) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS handler_reply varchar(5007) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS handled_at timestamp without time zone,
  ADD COLUMN IF NOT EXISTS sender_id integer,
  ADD COLUMN IF NOT EXISTS reported_user_id integer,
  ADD COLUMN IF NOT EXISTS handler_id integer,
  ADD COLUMN IF NOT EXISTS patch_id integer,
  ADD COLUMN IF NOT EXISTS comment_id integer,
  ADD COLUMN IF NOT EXISTS rating_id integer,
  ADD COLUMN IF NOT EXISTS created timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS updated timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE public.patch_resource
  ADD COLUMN IF NOT EXISTS storage varchar(107) NOT NULL DEFAULT 'user',
  ADD COLUMN IF NOT EXISTS section varchar(107) NOT NULL DEFAULT 'galgame',
  ADD COLUMN IF NOT EXISTS name varchar(300) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS size varchar(107) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS code varchar(1007) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS password varchar(1007) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS note varchar(10007) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS hash text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS content text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS type text[] NOT NULL DEFAULT ARRAY[]::text[],
  ADD COLUMN IF NOT EXISTS language text[] NOT NULL DEFAULT ARRAY[]::text[],
  ADD COLUMN IF NOT EXISTS platform text[] NOT NULL DEFAULT ARRAY[]::text[],
  ADD COLUMN IF NOT EXISTS download integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS status integer NOT NULL DEFAULT 0;

DO $$
BEGIN
  ALTER TABLE public.patch_report
    ADD CONSTRAINT patch_report_sender_id_fkey
    FOREIGN KEY (sender_id) REFERENCES public."user"(id)
    ON DELETE CASCADE ON UPDATE NO ACTION;
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN undefined_table THEN RAISE NOTICE 'Skipped patch_report_sender_id_fkey because a referenced table is missing.';
  WHEN undefined_column THEN RAISE NOTICE 'Skipped patch_report_sender_id_fkey because a referenced column is missing.';
END $$;

DO $$
BEGIN
  ALTER TABLE public.patch_report
    ADD CONSTRAINT patch_report_reported_user_id_fkey
    FOREIGN KEY (reported_user_id) REFERENCES public."user"(id)
    ON DELETE CASCADE ON UPDATE NO ACTION;
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN undefined_table THEN RAISE NOTICE 'Skipped patch_report_reported_user_id_fkey because a referenced table is missing.';
  WHEN undefined_column THEN RAISE NOTICE 'Skipped patch_report_reported_user_id_fkey because a referenced column is missing.';
END $$;

DO $$
BEGIN
  ALTER TABLE public.patch_report
    ADD CONSTRAINT patch_report_handler_id_fkey
    FOREIGN KEY (handler_id) REFERENCES public."user"(id)
    ON DELETE SET NULL ON UPDATE NO ACTION;
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN undefined_table THEN RAISE NOTICE 'Skipped patch_report_handler_id_fkey because a referenced table is missing.';
  WHEN undefined_column THEN RAISE NOTICE 'Skipped patch_report_handler_id_fkey because a referenced column is missing.';
END $$;

DO $$
BEGIN
  ALTER TABLE public.patch_report
    ADD CONSTRAINT patch_report_patch_id_fkey
    FOREIGN KEY (patch_id) REFERENCES public.patch(id)
    ON DELETE CASCADE ON UPDATE NO ACTION;
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN undefined_table THEN RAISE NOTICE 'Skipped patch_report_patch_id_fkey because a referenced table is missing.';
  WHEN undefined_column THEN RAISE NOTICE 'Skipped patch_report_patch_id_fkey because a referenced column is missing.';
END $$;

DO $$
BEGIN
  ALTER TABLE public.patch_report
    ADD CONSTRAINT patch_report_comment_id_fkey
    FOREIGN KEY (comment_id) REFERENCES public.patch_comment(id)
    ON DELETE SET NULL ON UPDATE NO ACTION;
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN undefined_table THEN RAISE NOTICE 'Skipped patch_report_comment_id_fkey because a referenced table is missing.';
  WHEN undefined_column THEN RAISE NOTICE 'Skipped patch_report_comment_id_fkey because a referenced column is missing.';
END $$;

DO $$
BEGIN
  ALTER TABLE public.patch_report
    ADD CONSTRAINT patch_report_rating_id_fkey
    FOREIGN KEY (rating_id) REFERENCES public.patch_rating(id)
    ON DELETE SET NULL ON UPDATE NO ACTION;
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN undefined_table THEN RAISE NOTICE 'Skipped patch_report_rating_id_fkey because a referenced table is missing.';
  WHEN undefined_column THEN RAISE NOTICE 'Skipped patch_report_rating_id_fkey because a referenced column is missing.';
END $$;

CREATE INDEX IF NOT EXISTS patch_report_status_target_type_created_idx
  ON public.patch_report (status, target_type, created DESC);

CREATE INDEX IF NOT EXISTS patch_report_target_type_comment_id_status_idx
  ON public.patch_report (target_type, comment_id, status);

CREATE INDEX IF NOT EXISTS patch_report_target_type_rating_id_status_idx
  ON public.patch_report (target_type, rating_id, status);

CREATE INDEX IF NOT EXISTS patch_report_sender_id_idx
  ON public.patch_report (sender_id);

CREATE INDEX IF NOT EXISTS patch_report_reported_user_id_idx
  ON public.patch_report (reported_user_id);

CREATE INDEX IF NOT EXISTS patch_report_patch_id_idx
  ON public.patch_report (patch_id);
