-- Production schema sync for the moemoepoint ledger and reservations.
-- Apply after reviewing production-moemoepoint-ledger-preflight-2026-08-17.sql.

\set ON_ERROR_STOP on
BEGIN;
SET LOCAL lock_timeout = '5s';

ALTER TABLE public."user"
  ADD COLUMN IF NOT EXISTS moemoepoint_reserved integer NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS public.user_moemoepoint_reservation (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  amount integer NOT NULL,
  status varchar(16) NOT NULL DEFAULT 'pending',
  reason_code varchar(64) NOT NULL,
  reason varchar(500) NOT NULL,
  reference_type varchar(64),
  reference_id varchar(191),
  link varchar(1000) NOT NULL DEFAULT '',
  idempotency_key varchar(191) NOT NULL,
  settlement_idempotency_key varchar(191),
  settlement_reason varchar(500),
  settled_at timestamp(3) without time zone,
  settled_by_id integer,
  created timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated timestamp(3) without time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS public.user_moemoepoint_ledger (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  kind varchar(32) NOT NULL,
  balance_delta integer NOT NULL,
  reserved_delta integer NOT NULL,
  balance_after integer NOT NULL,
  reserved_after integer NOT NULL,
  reason_code varchar(64) NOT NULL,
  reason varchar(500) NOT NULL,
  reference_type varchar(64),
  reference_id varchar(191),
  link varchar(1000) NOT NULL DEFAULT '',
  idempotency_key varchar(191),
  reservation_id integer,
  operator_id integer,
  created timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DO $$
BEGIN
  ALTER TABLE public.user_moemoepoint_reservation
    ADD CONSTRAINT user_moemoepoint_reservation_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public."user"(id)
    ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE public.user_moemoepoint_reservation
    ADD CONSTRAINT user_moemoepoint_reservation_settled_by_id_fkey
    FOREIGN KEY (settled_by_id) REFERENCES public."user"(id)
    ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE public.user_moemoepoint_ledger
    ADD CONSTRAINT user_moemoepoint_ledger_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public."user"(id)
    ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE public.user_moemoepoint_ledger
    ADD CONSTRAINT user_moemoepoint_ledger_reservation_id_fkey
    FOREIGN KEY (reservation_id) REFERENCES public.user_moemoepoint_reservation(id)
    ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE public.user_moemoepoint_ledger
    ADD CONSTRAINT user_moemoepoint_ledger_operator_id_fkey
    FOREIGN KEY (operator_id) REFERENCES public."user"(id)
    ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE public."user"
    ADD CONSTRAINT user_moemoepoint_reserved_nonnegative
    CHECK (moemoepoint_reserved >= 0);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE public.user_moemoepoint_reservation
    ADD CONSTRAINT user_moemoepoint_reservation_amount_positive
    CHECK (amount > 0);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE public.user_moemoepoint_reservation
    ADD CONSTRAINT user_moemoepoint_reservation_status_valid
    CHECK (status IN ('pending', 'released', 'forfeited'));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE public.user_moemoepoint_ledger
    ADD CONSTRAINT user_moemoepoint_ledger_reserved_after_nonnegative
    CHECK (reserved_after >= 0);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE public.user_moemoepoint_ledger
    ADD CONSTRAINT user_moemoepoint_ledger_kind_valid
    CHECK (kind IN (
      'opening', 'earn', 'spend', 'reserve', 'release',
      'forfeit', 'refund', 'reversal', 'adjustment'
    ));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS user_moemoepoint_reservation_idempotency_key_key
  ON public.user_moemoepoint_reservation (idempotency_key);
CREATE UNIQUE INDEX IF NOT EXISTS user_moemoepoint_reservation_settlement_idempotency_key_key
  ON public.user_moemoepoint_reservation (settlement_idempotency_key);
CREATE INDEX IF NOT EXISTS user_moemoepoint_reservation_user_id_status_created_idx
  ON public.user_moemoepoint_reservation (user_id, status, created DESC);
CREATE INDEX IF NOT EXISTS user_moemoepoint_reservation_settled_by_id_idx
  ON public.user_moemoepoint_reservation (settled_by_id);

CREATE UNIQUE INDEX IF NOT EXISTS user_moemoepoint_ledger_idempotency_key_key
  ON public.user_moemoepoint_ledger (idempotency_key);
CREATE INDEX IF NOT EXISTS user_moemoepoint_ledger_user_id_created_id_idx
  ON public.user_moemoepoint_ledger (user_id, created DESC, id DESC);
CREATE INDEX IF NOT EXISTS user_moemoepoint_ledger_reservation_id_idx
  ON public.user_moemoepoint_ledger (reservation_id);
CREATE INDEX IF NOT EXISTS user_moemoepoint_ledger_operator_id_idx
  ON public.user_moemoepoint_ledger (operator_id);
CREATE INDEX IF NOT EXISTS user_status_moemoepoint_id_idx
  ON public."user" (status, moemoepoint DESC, id);

INSERT INTO public.user_moemoepoint_ledger (
  user_id,
  kind,
  balance_delta,
  reserved_delta,
  balance_after,
  reserved_after,
  reason_code,
  reason,
  idempotency_key
)
SELECT
  id,
  'opening',
  moemoepoint,
  0,
  moemoepoint,
  moemoepoint_reserved,
  'system.migration_opening',
  '系统迁移初始余额',
  'moemoepoint:opening:' || id
FROM public."user"
ON CONFLICT (idempotency_key) DO NOTHING;

COMMIT;
