-- Production schema sync for private-chat sticker packs.
-- This script is non-destructive: it creates missing sticker catalog tables
-- and adds nullable message references without deleting existing messages.

CREATE TABLE IF NOT EXISTS public.sticker_pack (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug varchar(100) NOT NULL,
  name varchar(100) NOT NULL,
  description varchar(500) NOT NULL DEFAULT '',
  cover_url varchar(1000),
  price integer NOT NULL DEFAULT 0,
  status integer NOT NULL DEFAULT 1,
  is_builtin boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE public.sticker_pack
  ADD COLUMN IF NOT EXISTS slug varchar(100) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS name varchar(100) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS description varchar(500) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS cover_url varchar(1000),
  ADD COLUMN IF NOT EXISTS price integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS status integer NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS is_builtin boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS sort_order integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS created timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS updated timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX IF NOT EXISTS sticker_pack_slug_key
  ON public.sticker_pack (slug);
CREATE INDEX IF NOT EXISTS sticker_pack_status_sort_order_idx
  ON public.sticker_pack (status, sort_order);

CREATE TABLE IF NOT EXISTS public.sticker (
  id varchar(100) PRIMARY KEY,
  pack_id integer NOT NULL,
  alt varchar(255) NOT NULL DEFAULT '',
  asset_url varchar(1000) NOT NULL,
  thumbnail_url varchar(1000),
  storage_key varchar(500) NOT NULL,
  thumbnail_storage_key varchar(500),
  mime varchar(100) NOT NULL,
  media_type varchar(16) NOT NULL DEFAULT 'image',
  width integer NOT NULL DEFAULT 0,
  height integer NOT NULL DEFAULT 0,
  size integer NOT NULL DEFAULT 0,
  duration_ms integer,
  frame_rate double precision,
  sort_order integer NOT NULL DEFAULT 0,
  created timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE public.sticker
  ADD COLUMN IF NOT EXISTS pack_id integer,
  ADD COLUMN IF NOT EXISTS alt varchar(255) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS asset_url varchar(1000) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS thumbnail_url varchar(1000),
  ADD COLUMN IF NOT EXISTS storage_key varchar(500) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS thumbnail_storage_key varchar(500),
  ADD COLUMN IF NOT EXISTS mime varchar(100) NOT NULL DEFAULT 'image/webp',
  ADD COLUMN IF NOT EXISTS media_type varchar(16) NOT NULL DEFAULT 'image',
  ADD COLUMN IF NOT EXISTS width integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS height integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS size integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS duration_ms integer,
  ADD COLUMN IF NOT EXISTS frame_rate double precision,
  ADD COLUMN IF NOT EXISTS sort_order integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS created timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS updated timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;

DO $$
BEGIN
  ALTER TABLE public.sticker
    ADD CONSTRAINT sticker_pack_id_fkey
    FOREIGN KEY (pack_id) REFERENCES public.sticker_pack(id)
    ON DELETE RESTRICT ON UPDATE NO ACTION;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS sticker_pack_id_sort_order_idx
  ON public.sticker (pack_id, sort_order);

CREATE TABLE IF NOT EXISTS public.user_sticker_pack (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  pack_id integer NOT NULL,
  price_paid integer NOT NULL DEFAULT 0,
  source varchar(32) NOT NULL DEFAULT 'builtin',
  acquired_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT user_sticker_pack_user_id_pack_id_key UNIQUE (user_id, pack_id)
);

ALTER TABLE public.user_sticker_pack
  ADD COLUMN IF NOT EXISTS price_paid integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS source varchar(32) NOT NULL DEFAULT 'builtin',
  ADD COLUMN IF NOT EXISTS acquired_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS created timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS updated timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;

DO $$
BEGIN
  ALTER TABLE public.user_sticker_pack
    ADD CONSTRAINT user_sticker_pack_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public."user"(id)
    ON DELETE CASCADE ON UPDATE NO ACTION;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE public.user_sticker_pack
    ADD CONSTRAINT user_sticker_pack_pack_id_fkey
    FOREIGN KEY (pack_id) REFERENCES public.sticker_pack(id)
    ON DELETE CASCADE ON UPDATE NO ACTION;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS user_sticker_pack_user_id_pack_id_key
  ON public.user_sticker_pack (user_id, pack_id);
CREATE INDEX IF NOT EXISTS user_sticker_pack_pack_id_idx
  ON public.user_sticker_pack (pack_id);

ALTER TABLE public.user_private_message
  ADD COLUMN IF NOT EXISTS sticker_id varchar(100),
  ADD COLUMN IF NOT EXISTS reply_sticker_id varchar(100);

DO $$
BEGIN
  ALTER TABLE public.user_private_message
    ADD CONSTRAINT user_private_message_sticker_id_fkey
    FOREIGN KEY (sticker_id) REFERENCES public.sticker(id)
    ON DELETE SET NULL ON UPDATE NO ACTION;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE public.user_private_message
    ADD CONSTRAINT user_private_message_reply_sticker_id_fkey
    FOREIGN KEY (reply_sticker_id) REFERENCES public.sticker(id)
    ON DELETE SET NULL ON UPDATE NO ACTION;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS user_private_message_sticker_id_idx
  ON public.user_private_message (sticker_id);
CREATE INDEX IF NOT EXISTS user_private_message_reply_sticker_id_idx
  ON public.user_private_message (reply_sticker_id);
